import { ApolloWrapper } from "../graphql/client";
import { CssBaseline, Container } from "@mui/material";
import AppHeader from "../components/header";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CssBaseline />
        <ApolloWrapper>
          <AppHeader />
          <Container maxWidth="lg" sx={{ my: 4 }}>
            {children}
          </Container>
        </ApolloWrapper>
      </body>
    </html>
  );
}
