# Set the maximum line length to 80.
line-length = 80

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # flake8-async
    "ASYNC",
    # flake8-logging-format
    "G",
]
extend-select = [
    # Add the `line-too-long` rule to the enforced rule set.
    "E501",
]

[format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true
