name: Chat Service

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r chat_service/dependencies.txt

      - name: Generate Proto files
        working-directory: chat_service
        run: |
          python -m grpc_tools.protoc -I src/proto --proto_path=src/generated/ --python_out=src/generated/ --pyi_out=src/generated/ --grpc_python_out=src/generated/ src/proto/chat_service.proto

      - name: Lint with ruff
        run: ruff check

      - name: Test with pytest
        run: pytest

      - name: Start chat service and perform health check
        working-directory: chat_service
        run: |
          python src/server.py &
          SERVER_PID=$!
          sleep 5
          python src/client.py
          kill $SERVER_PID
