name: Backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint-and-test-backend:
    # CI Machine OS
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: mysql+pymysql://testuser:testpassword@127.0.0.1:3306/testdb
      DATABASE_HOST: 127.0.0.1
      DATABASE_USERNAME: testuser
      DATABASE_PASSWORD: testpassword
      DATABASE_NAME: testdb

    # MySQL service
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpassword
        ports:
          - "3306:3306"
        options: "--health-cmd=\"mysqladmin ping -uroot -ptestpassword || exit 1\" --health-interval=10s --health-timeout=5s --health-retries=5"
        
    steps:
      # Checkout commit
      - uses: actions/checkout@v4

      # Install Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/dependencies.txt

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -u testuser --password=testpassword; then
              echo "MySQL is up"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      # Run linter
      - name: Lint with ruff
        run: ruff check

      # Run tests
      - name: Test with pytest
        env:
          DATABASE_URL: mysql+pymysql://testuser:testpassword@127.0.0.1:3306/testdb
        run: pytest

      # Start server
      - name: Start server
        working-directory: backend
        run: |
          uvicorn src.server:app --host 0.0.0.0 --port 8000 &

      # Perform Health Check
      - name: Wait for FastAPI server
        run: |
          for i in {1..30}; do
            if curl --fail http://localhost:8000/health; then
              echo "Server is up"
              break
            fi
            echo "Waiting for FastAPI..."
            sleep 2
          done

