name: Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint-and-test-backend:
    # CI Machine OS
    runs-on: ubuntu-latest

    steps:
      # Checkout commit
      - uses: actions/checkout@v4

      # Install Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/dependencies.txt

      # Run linter
      - name: Lint with ruff
        run: ruff check

      # Run tests
      - name: Test with pytest
        run: pytest

      # Start server
      - name: Start server
        run: |
          nohup uvicorn backend.app:app --host 0.0.0.0 --port 8000 &

      # Wait for server to start
      - name: Wait for server to start
        run: sleep 10

      # Perform Health Check
      - name: Perform Health Check
        run: |
          curl --fail http://localhost:8000/health || exit 1
