name: Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint-build-and-test:
    # CI Machine OS
    runs-on: ubuntu-latest

    steps:
      # Checkout commit
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        working-directory: frontend
        run: 
          npm install

      # Run linter
      - name: Run linter
        working-directory: frontend
        run: |
          npm run lint

      # Run tests
      - name: Run tests
        working-directory: frontend
        run: |
          npm test

      # Build the app
      - name: Build the React app
        working-directory: frontend
        run: |
          npm run build